server:
  port: 8001
rpc:
  token: timu.fun
spring:
  application:
    name: cloud-account
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 327d6e78-c121-4c52-b83f-1c5c0da33f61
  redis:
    client-type: jedis
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000


  # 数据源 ds0 第一个数据库
  shardingsphere:
    datasource:
      #数据源名称
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://127.0.0.1:3306/cloud_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: 123456

    props:
      # 打印执行的数据库以及语句
      sql:
        show: true

    sharding:
      tables:
        traffic:
          # 指定traffic表的数据分布情况，配置数据节点,行表达式标识符使用 ${...} 或 $->{...}，但前者与 Spring 本身的文件占位符冲突，所以在 Spring 环境中建议使用 $->{...}
          actual-data-nodes: ds0.traffic_$->{0..1}
          #水平分表策略+行表达式分片
          table-strategy:
            inline:
              algorithm-expression: traffic_$->{ account_no % 2 }
              sharding-column: account_no
          #id生成策略
          key-generator:
            column: id
            props:
              worker:
                id: ${workId}
            #id生成策略
            type: SNOWFLAKE

  # RabbitMQ服务配置
  rabbitmq:
    # RabbitMQ服务器地址
    host: 127.0.0.1
    # 消息监听器配置
    listener:
      simple:
        # 确认模式，自动确认消息处理
        acknowledge-mode: auto
        # 重试机制配置
        retry:
          # 启用重试功能
          enabled: true
          # 初始重试间隔时间，单位为毫秒
          initial-interval: 5000
          # 最大重试次数
          max-attempts: 4
    # RabbitMQ登录密码
    password: admin
    # RabbitMQ服务端口
    port: 5672
    # RabbitMQ登录用户名
    username: admin
    # 虚拟主机名称，用于隔离不同的环境
    virtual-host: dev

#----------阿里云OSS配置--------------
#aliyun:
#  oss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    access-key-id: Key
#    access-key-secret: Secret
#    bucketname: 桶名

logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: timu.fun
    admin:
      addresses: http://127.0.0.1:18080/xxl-job-admin
    executor:
      address: ''
      appname: traffic-app-executor
      ip: ''
      logpath: ./data/logs/xxl-job/executor
      logretentiondays: 30
      port: 9999
