server:
  port: 8002
spring:
  application:
    name: cloud-data
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.108:8848
        namespace: 327d6e78-c121-4c52-b83f-1c5c0da33f61
  datasource:
    #数据库配置
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://192.168.0.108:8123/default
  redis:
    client-type: jedis
    host: 192.168.0.108
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info