server:
  port: 8003
spring:
  application:
    name: cloud-link
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 327d6e78-c121-4c52-b83f-1c5c0da33f61

  # 数据源 ds0 第一个数据库
  shardingsphere:
    datasource:
      #数据源名称
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://127.0.0.1:3306/cloud_link?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: 123456

    props:
      # 打印执行的数据库以及语句
      sql:
        show: true

    sharding:
      tables:
        link_group:
          key-generator:
            column: id
            props:
              worker:
                id: ${workId}
            #id生成策略
            type: SNOWFLAKE
