server:
  port: 8004
spring:
  application:
    name: cloud-shop
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 327d6e78-c121-4c52-b83f-1c5c0da33f61
  # 数据源 ds0 第一个数据库
  shardingsphere:
    datasource:
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://127.0.0.1:3306/cloud_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      names: ds0
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: ds0
      default-key-generator:
        column: id
        props:
          worker:
            id: ${workerId}
        type: SNOWFLAKE
      tables:
        product_order:
          actual-data-nodes: ds0.product_order_$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: product_order_$->{ account_no % 2 }
              sharding-column: account_no
